### ISSUE TITLE
Uncommon light / dark switcher

### ISSUE THREAD

**Issue by peteruithoven** [Mohelm97/screenrecorder#1]
To be more consistent with other parts of elementary OS it might be interesting to use the `Granite.ModeSwitch`, like for example the Granite demo uses. 
![screenshot from 2018-12-13 12 10 42](https://user-images.githubusercontent.com/523210/49935128-7686d280-fed0-11e8-8ab5-37da5db0876d.png)
Or like many other apps not include a UI to change this at all.

I love this app btw! It already seems to work better than Screencast and Peek.

**Comment by mohelm97** [comment]
@peteruithoven Ohh thanks a lot mate for this nice comment first, And yeah I think now it looks better :D 
16a2ce519f5ed5dc73dc804bd32bb64825b91f59

**Comment by peteruithoven** [comment]
Thanks!
