### ISSUE TITLE
Saved notification?

### ISSUE THREAD

**Issue by peteruithoven** [Mohelm97/screenrecorder#11]
Seeing that encoding & saving can take quite a while I'd love a notification when it's done, a bit like Terminal when it's running in the background.

**Comment by peteruithoven** [comment]
Similar plans for notifications after taking screenshots with Gala: https://github.com/elementary/gala/issues/137

**Comment by mohelm97** [comment]
@peteruithoven yeah we need this especially after adding rendering options.

**Comment by mohelm97** [comment]
Done 4a1d932936d4fb1248a8ffe986bd942b906654d9 ;)

**Comment by peteruithoven** [comment]
Noice!
