### ISSUE TITLE
Start & stop recording keyboard shortcuts?

### ISSUE THREAD

**Issue by peteruithoven** [Mohelm97/screenrecorder#2]
Because the placement of the mouse can be important in recordings I'd love to be able to start and stop recordings with keyboard shortcuts. 
- Screencast for example listens to media keys to control recording (https://github.com/artemanufrij/screencast/issues/25)
- SimpleSceenRecording supports toggling recording using by default <kbd>Ctrl</kbd>+<kbd>R</kbd>.

**Comment by mohelm97** [comment]
Yeah, I think this is essential, right now I will work on it but I'm not sure about which keys, I like the Screencast logic but not sure yet if you have any suggestion it would be awesome :tada:

**Comment by peteruithoven** [comment]
Which ever keys you choose to use it might be interesting to communicate it by adding a tooltip to the record button. I recommend you use the [`Granite.markup_accel_tooltip`](https://github.com/elementary/granite/blob/master/lib/Widgets/Utils.vala#L155) function. 
It's also used for the Applications menu tooltip and (upcoming versions of) Files, Calendar, Code and Terminal. 
Hopefully that consistency will increase the discoverability.

**Comment by mohelm97** [comment]
Thanks, @peteruithoven, I've added this, not sure if my method to create a global hotkey is good or there's something better (If you know please tell me), you can check the key by the tooltip haha :D 
Also, I'm not satisfied with the saving mechanism if you have a better idea let me know.

**Comment by aral** [comment]
Just a heads up: a tooltip is a hidden gesture. Case in point: I came over here to try and find out what the keyboard shortcut is :)

It would be easier to people to find if it was visible by default. e.g., in the interface footer.

**Comment by samuellealb** [comment]
Was this implemented?

**Comment by ulvido** [comment]
> Thanks, @peteruithoven, I've added this, not sure if my method to create a global hotkey is good or there's something better (If you know please tell me), you can check the key by the tooltip haha :D
> Also, I'm not satisfied with the saving mechanism if you have a better idea let me know.

very very cool but it is hard to see the tooltip for newcomers. I came here to findout about record hotkeys keys. now I can't unsee it is good but as a new user perspective I couldn't be able to find by myself.

Edit: on the search of a shortcut before coming to github, I checked elementary app page first. Maybe writing a little new line "You can press Ctrl + Shift + R to start and stop recording" would help. I think you don't need to change anything in the app. it is perfect.

![2021-08-21 08-53-57 ekran görüntüsü](https://user-images.githubusercontent.com/27722274/130312117-d59daf4b-e95e-4ef9-b5b6-ffbaab07fc44.png)
