### ISSUE TITLE
Use GLib.AppInfo to launch default app

### ISSUE THREAD

**Issue by danirabbit** [Mohelm97/screenrecorder#21]
https://github.com/Mohelm97/screenrecorder/blob/303c0ed0c4006b68a80c57b4599d25b55054b73c/src/Application.vala#L53

This can be done by using [GLib.AppInfo.launch_default_for_uri](https://valadoc.org/gio-2.0/GLib.AppInfo.launch_default_for_uri.html) instead of with a command

**Comment by peteruithoven** [comment]
Example: https://stackoverflow.com/questions/54886411/open-file-with-default-application-from-vala/54895789#54895789

**Comment by mohelm97** [comment]
Fixed 7faf4df8b2c8e512f2e89a0bbe6a6e1424127c1d
@danrabbit @peteruithoven  Thanks a lot 
I feel so dump :D
