### ISSUE TITLE
What License does this project use?

### ISSUE THREAD

**Issue by worldofpeace** [Mohelm97/screenrecorder#22]

**Comment by mohelm97** [comment]
GPL-3.0 ;)

**Comment by worldofpeace** [comment]
https://github.com/Mohelm97/screenrecorder/blob/0e4f97981123153e1c4f9cda3e91636dacef3c28/debian/copyright says GPL-3.0+

Can you maybe do https://help.github.com/en/articles/licensing-a-repository?

A note in the README.md would be helpful as well.

**Comment by mohelm97** [comment]
@worldofpeace I've added a license here
https://github.com/Mohelm97/screenrecorder/blob/master/COPYING

**Comment by worldofpeace** [comment]
Thank you :+1: 

This especially helps for people who'd like to package this in their respective distro.
