### ISSUE TITLE
Issue with translations

### ISSUE THREAD

**Issue by NathanBnm** [Mohelm97/screenrecorder#24]
Hi! I made a PR to add translations but they aren't working in the last update, like if they were not implemented.

However I tried to build the app from source and this is working well.

I don't know where's the issue.

**Comment by ryonakano** [comment]
![Screenshot from 2019-09-20 22-29-15](https://user-images.githubusercontent.com/26003928/65331261-6a663900-dbf7-11e9-9ef5-299118dce800.png)

@NathanBnm I installed the app from AppCenter, tried launching the app in French (with `LANGUAGE=fr com.github.mohelm97.screenrecorder`) and I can't confirm this issue. Are you still facing this issue?

**Comment by NathanBnm** [comment]
I'm gonna check this again as soon as I will have elementary OS reinstalled.

**Comment by ryonakano** [comment]
@NathanBnm Wanna take another look?

**Comment by NathanBnm** [comment]
@ryonakano I tried with my new installation and this is working well. I still don't know why I was experiencing this issue. Closing.
