### ISSUE TITLE
Error saving very large videos

### ISSUE THREAD

**Issue by gustavoedny** [Mohelm97/screenrecorder#29]
Hi, I'm using this program to record some videos in my elementary os. More I can not record videos with another 5 minutes, when I stop recording my screen the app stops responding and I end up losing everything I recorded.

These are the configurations of my machine:

Lenovo Ideapad 320 - Inter core i7-75OOu
Ram Memory 16GB
GeForce 940MX 4GB Video Card

**Comment by mohelm97** [comment]
Thanks a lot, @GustavoEdny, I can confirm this issue, I will try to fix it now ;)

**Comment by gustavoedny** [comment]
Is this already available in the elementary store?

**Comment by mohelm97** [comment]
@GustavoEdny Not yet :(, I will add a new release after fixing some issues and add some stuff :D
