### ISSUE TITLE
HiDPI Video player in save window issue

### ISSUE THREAD

**Issue by peteruithoven** [Mohelm97/screenrecorder#3]
It looks like the video is showed to big on HiDPI screens in the save window:
![screenshot from 2018-12-15 09 49 50](https://user-images.githubusercontent.com/523210/50041060-d99e7380-004e-11e9-90a2-dbe1198c7e92.png)

**Comment by mohelm97** [comment]
Opss, My bad multiplication instead of division, Done ;)

**Comment by peteruithoven** [comment]
Works perfectly now, thanks!
![screenshot from 2018-12-15 10 57 25](https://user-images.githubusercontent.com/523210/50041640-3f432d80-0058-11e9-9c17-4916e7789b0c.png)

**Comment by DanyGee** [comment]
This is what I encountered while trying to save a record on hidpi screen.
The preview window cannot be resized or moved of the screen to reach Save buttons.
![Screenshot from 2019-08-22 19 27 47@2x](https://user-images.githubusercontent.com/26818551/63536071-22c69180-c513-11e9-8cce-e3426f1c5e74.png)
