### ISSUE TITLE
Only record audio

### ISSUE THREAD

**Issue by leehblue** [Mohelm97/screenrecorder#31]
Feature request: I would LOVE a setting where you can record just the desktop audio and mic audio as an MP3. I do a lot of audio interviews for podcasts and would love a clean simple app like yours instead of having to use OBS for recording audio podcasts. I do the calls over Skype and a simple way to record the audio would be awesome.

**Comment by peteruithoven** [comment]
Wouldn't it make more sense to use an app like [Reco](https://appcenter.elementary.io/com.github.ryonakano.reco/) for that though? 
Looks like people are working on support for recording system audio: https://github.com/ryonakano/reco/pull/31

**Comment by peteruithoven** [comment]
This has now been [implemented](https://github.com/ryonakano/reco/pull/31) and [released](https://github.com/ryonakano/reco/releases/tag/2.0.0) by Reco.
