### ISSUE TITLE
Hangs my system every time recording is stopped

### ISSUE THREAD

**Issue by Gabriel-p** [Mohelm97/screenrecorder#34]
The system freezes completely and can not be recovered.

![Captura de pantalla de 2019-08-23 11-39-04](https://user-images.githubusercontent.com/6054951/63600813-a8415480-c59a-11e9-8858-25583991772c.png)

**Comment by mohelm97** [comment]
He @Gabriel-p 
Could you post more information about this?
(e.g. running it from the terminal and post the log)
Sorry for this mate :(

**Comment by Gabriel-p** [comment]
Sorry @Mohelm97 but that means freezing my system completely to obtain that output and I don't have the time to do that. I understand the issue as it stands is probably worthless without more info, so I'll just close it. Cheers

(And no need to apologize! Thank you for making free open source software!)
