### ISSUE TITLE
Save video preview only loads small videos

### ISSUE THREAD

**Issue by peteruithoven** [Mohelm97/screenrecorder#4]
I love the potential of the video preview, but after recording a larger area the save window doesn't seem to load the preview.
![screenshot from 2018-12-15 09 42 33](https://user-images.githubusercontent.com/523210/50041197-3b5fdd00-0051-11e9-896c-9bea9b45a4b6.png)

It seems to happen for both mp4 and gif. Other settings:
![screenshot from 2018-12-15 09 48 05](https://user-images.githubusercontent.com/523210/50041036-9217e780-004e-11e9-8ed8-84b68fa4467d.png)

Logs:
```
$ G_MESSAGES_DEBUG=all com.github.mohelm97.screenrecorder 
(com.github.mohelm97.screenrecorder:24644): Gtk-DEBUG: 10:03:00.814: Connecting to session manager
** (com.github.mohelm97.screenrecorder:24644): DEBUG: 10:03:00.933: KeybindingManager.vala:76: Binding key <Ctrl><Shift>R
** (com.github.mohelm97.screenrecorder:24644): DEBUG: 10:03:00.934: KeybindingManager.vala:106: Successfully binded key <Ctrl><Shift>R
** (com.github.mohelm97.screenrecorder:24644): DEBUG: 10:03:07.143: MainWindow.vala:293: Temp file created at: /tmp/screenrecorder-61575624.mp4
** (com.github.mohelm97.screenrecorder:24644): DEBUG: 10:03:07.143: FFmpegWrapper.vala:80: ffmpeg command: ffmpeg -y -video_size 1330x910 -framerate 30 -show_region 1 -region_border 2 -draw_mouse 1 -f x11grab -i :0+2122,494 -preset ultrafast /tmp/screenrecorder-61575624.mp4
```

Unsurprisingly it also happens when I record the whole screen. 

When this happens I notice the UI is also impacted, it still switches the cursor to text cursor for example, but I can't select parts of the file name. I can still click the cancel button, but no down state is shown.
![peek 2018-12-15 10-16](https://user-images.githubusercontent.com/523210/50041276-b4abff80-0052-11e9-988b-2a1b9307fcb1.gif)

**Comment by mohelm97** [comment]
Can you try it now with HiDPI fix?
Or do you mean small by the length?

**Comment by peteruithoven** [comment]
I'm afraid the issue remains with the HiDPI fix. 
It works great when I record a longer video with small dimensions, but when recording a larger area I run into the issue.

**Comment by mohelm97** [comment]
Not sure why is this happing, I will try to install a virtual machine with HiDPI to test it, as on my normal resolution it works fine.

**Comment by mohelm97** [comment]
Wooh :D 
Not sure but I think now it should work, I've used ClutterGst instead of direct gstreamer.

**Comment by peteruithoven** [comment]
Works like a dream now! It's such an improvement to get an immediate preview of a recording you want to save as a gif.
