### ISSUE TITLE
Export to GIF

### ISSUE THREAD

**Issue by Fatih20** [Mohelm97/screenrecorder#54]
Videos can't be shared through internet forums or even github. Enabling exporting to GIF would make it easier to do this.

**Comment by peteruithoven** [comment]
Am I missing something?
![Screenshot from 2020-05-26 09 52 25@2x](https://user-images.githubusercontent.com/523210/82874750-b4e24700-9f36-11ea-9c7b-cdc582a0780f.png)

**Comment by Fatih20** [comment]
Whoops, dumb me.
