### ISSUE TITLE
Add FFMpeg to your runtime dependencies

### ISSUE THREAD

**Issue by danirabbit** [Mohelm97/screenrecorder#7]
Your app doesn't currently actually record anything due to:

`
** (com.github.mohelm97.screenrecorder:5629): WARNING **: 09:10:24.087: FFmpegWrapper.vala:86: Failed to execute child process “ffmpeg” (No such file or directory)
`

You'll need to add FFMpeg to your runtime dependencies so that it gets pulled in when users install your app

https://github.com/Mohelm97/screenrecorder/blob/991263f3f5fdd6550b4b63abe85fc7d9bd024727/debian/control#L18

**Comment by mohelm97** [comment]
Opss, Thanks mate ;)
353d127a9016e889e663fc9d6b8680e1ea25a1ca
