### ISSUE TITLE
Downscale option?

### ISSUE THREAD

**Issue by peteruithoven** [Mohelm97/screenrecorder#9]
When recording fullscreen screen recordings to gif it's pretty easy to get very big files, especially when using HiDPI / 4k screens. 
12 fps screen recordings of maybe 2 seconds from my 4k screen already become 13 to 24MB, while Github has set it's upload limit to 10MB. 
I'd love an option in the save and preview window to downscale the saved video, for example x times smaller or by setting a max width / height (whatever is easier for you).

(In the end I was able to create a 5.6MB file by removing all photographic materials from the screen)

**Comment by peteruithoven** [comment]
Looks like [Peek](https://github.com/phw/peek) supports this with a "resolution downsampling" option (https://github.com/phw/peek/pull/45/files). 
I would love to find a more easy to understand name.

**Comment by peteruithoven** [comment]
Looks like Peek is using a scale filter: https://github.com/phw/peek/blob/master/src/recording/ffmpeg-screen-recorder.vala#L46
Docs: https://ffmpeg.org/ffmpeg-filters.html#scale-1
So maybe a "scale" option? Seems way more understandable than "resolution downsampling".
Maybe a 1 to 100 value with % unit in the UI?

**Comment by peteruithoven** [comment]
(I'm working on a PR)

**Comment by mohelm97** [comment]
Heey @peteruithoven, thanks a lot for the PR, I'm traveling this week so that's why I'm not active :(
I will be home next week 😁
Cheers ;)

**Comment by mohelm97** [comment]
@peteruithoven Thanks a lot mate ;) 
I'm really sad that it took me one month to say anything :( I'm really appreciating your awesome work <3 thanks again ;)
but Hooray I'm finally home and settled :D
